name: Build

on:
  push:
    branches:
      - dev
      - release
      - prerelease
  pull_request:
    branches:
      - dev
      - release
      - prerelease

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
          
    steps:
    - uses: actions/checkout@v2
    - name: Clean dependencies
      run: |
        dotnet clean Mutagen.Bethesda.Serialization.sln -c Release
        dotnet clean Mutagen.Bethesda.Serialization.Tests.sln -c Release
        dotnet nuget locals all --clear
    - name: Install dependencies for Main Solution
      run: dotnet restore Mutagen.Bethesda.Serialization.sln
    - name: Build Main Solution
      run: dotnet build Mutagen.Bethesda.Serialization.sln -c Release --no-restore /p:GeneratePackageOnBuild=false
    - name: Test Main Solution
      run: dotnet test Mutagen.Bethesda.Serialization.sln -c Release --no-build
    - name: Install dependencies for Test Solution
      run: dotnet restore Mutagen.Bethesda.Serialization.Tests.sln
    - name: Build Test Solution
      run: dotnet build Mutagen.Bethesda.Serialization.Tests.sln -c Release --no-restore /p:GeneratePackageOnBuild=false
    - name: Test Test Solution
      run: dotnet test Mutagen.Bethesda.Serialization.Tests.sln -c Release --no-build
