name: Build

on:
  push:
    branches:
      - dev
      - main
      - prerelease
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - dev
      - main
      - prerelease
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.0.5'
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.0.3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.*
      - name: Clean dependencies
        run: |
          dotnet clean Mutagen.Bethesda.Serialization.sln -c Release
          dotnet clean Mutagen.Bethesda.Serialization.Tests.sln -c Release
          dotnet nuget locals all --clear
      - name: Build Main Solution
        run: dotnet build Mutagen.Bethesda.Serialization.sln -c Release -p:GitVersion_NuGetVersion=${{ steps.version_step.outputs.fullSemVer }}
      - name: Test Main Solution
        run: dotnet test Mutagen.Bethesda.Serialization.sln -c Release --no-build -p:GitVersion_NuGetVersion=${{ steps.version_step.outputs.fullSemVer }}
      - name: Add results to local nuget cache
        run: |
          workingDir="$(cd "$(dirname "./")"; pwd)/$(basename "./")"
          echo "workingDir=$workingDir"
          dotnet nuget add source "${workingDir}/nupkg" --name SelfNugetPackages
          dotnet nuget enable source SelfNugetPackages
      - name: Build Test Solution
        run: dotnet build Mutagen.Bethesda.Serialization.Tests.sln -c Release /p:GeneratePackageOnBuild=false -p:GitVersion_NuGetVersion=${{ steps.version_step.outputs.fullSemVer }}
      - name: Test Test Solution
        run: dotnet test Mutagen.Bethesda.Serialization.Tests.sln -c Release --no-build -p:GitVersion_NuGetVersion=${{ steps.version_step.outputs.fullSemVer }}
